site_name: Rusty Bargain App
theme:
  name: material
  palette:
    primary: blue
  language: en

repo_name: "Rusty-Bargain-App"
repo_url: "https://github.com/realdanizilla/Rusty-Bargain-App"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
nav:
  - Home: index.md
  - API: api.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
